language: cpp
compiler:
  - g++
  - clang

script:
  - mkdir build
  - cd build
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ctest

addons:
  apt:
    packages: lcov

after_success:
  - cmake --build . --target coveralls

notifications:
  email: false


